package hr.hrg.hipster.entity;

import java.lang.reflect.*;
import java.util.*;
import java.util.concurrent.*;

import hr.hrg.hipster.sql.*;

@SuppressWarnings("rawtypes")
public class EntitySource implements Iterable<IEntityMeta<?,?>>{
	protected Map<Class<? extends Object>, IEntityMeta<?,?>> registered = new ConcurrentHashMap<>(); 
	protected Map<String, IEntityMeta<?,?>> named = new ConcurrentHashMap<>();
	protected Map<Class, IEntityMeta<?,?>> metaInstance = new ConcurrentHashMap<>();

	private int entityIndex = 0;
	private HipsterSql hip;

	public EntitySource() {
	}
	
	public EntitySource(HipsterSql hip) {
		this.hip = hip;
	}
	
	protected <T> void registerFor(IEntityMeta<T, ?> meta){
		registerFor(meta, meta.getEntityClass());
		
		for(Class clazz:meta.getImplClasses()) {
			registerFor(meta, clazz);
		}
	}

	public Iterator<IEntityMeta<?,?>> iterator(){
		return metaInstance.values().iterator();
	}
	
	public <T> void registerFor(IEntityMeta<T, ?> meta, Class<T> clazz){
		registered.put(clazz, meta);
		metaInstance.put(meta.getClass(), meta);
		named.put(clazz.getSimpleName(), meta);
	}

	public <T> T getMetaInstance(Class<T> clazz){
		return (T) metaInstance.get(clazz);
	}
	
	public <T> T getMetaInstanceRequired(Class<T> clazz){
		T ret = (T) metaInstance.get(clazz);

		if(ret == null) throw new RuntimeException("Meta not found for "+clazz.getName());

		return ret;
	}

	@SuppressWarnings("unchecked")
	public <T> IEntityMeta<T, ?> getFor( Class<T> clazz){
		IEntityMeta<T, ?> ret = (IEntityMeta<T, ?>) registered.get(clazz);
		if(ret == null){
			ret = (IEntityMeta<T, ?>) loadHandlerFromClass(HipsterSqlUtil.entityNamesPrefix(clazz)+"Meta");
			if(ret != null) registerFor(ret, clazz);
		}
		return ret;
	}
	
	public <T> IEntityMeta<T, ?> getForRequired( Class<T> clazz){
		IEntityMeta<T, ?> ret = getFor(clazz);
		
		if(ret == null) throw new RuntimeException("Meta not found for "+clazz.getName());
		
		return ret;
	}

	public IEntityMeta<?, ?> getFor(String name){
		return named.get(name);
	}

	public IEntityMeta<?, ?> getForRequired(String name){
		IEntityMeta<?, ?> ret = named.get(name);
		
		if(ret == null) throw new RuntimeException("Meta not found for "+name);

		return ret;
	}

	public IEntityMeta<?,?> loadHandlerFromClass(String cName) {
		if(hip == null) return null;
		try {
			Class<?> meta = Class.forName(cName);
			// found if no exception, now we just need to construct new instance
			if(IEntityMeta.class.isAssignableFrom(meta)) {				
				return newInstance(meta);
			}
		} catch (ClassNotFoundException e) {
			// ok, no Meta generated by hipster-processor
		} catch (Exception e) {
			throw new RuntimeException("Found possible generated Visitor handler class, but faild to instantiate ",e);
		}
		return null;
	}

	protected IEntityMeta<?, ?> newInstance(Class<?> meta)	throws InstantiationException, IllegalAccessException, InvocationTargetException, NoSuchMethodException {
		return (IEntityMeta<?, ?>) meta.getConstructor(new Class<?>[]{HipsterSql.class, int.class}).newInstance(hip, entityIndex++);
	}

	@SafeVarargs
	public final void register(Class<? extends IEntityMeta> ...metas ){
		try {			
			for (Class<? extends IEntityMeta> meta : metas) {
				IEntityMeta<?, ?> instance = newInstance(meta);
				registerFor(instance);
			}
		} catch (Exception e) {
			throw new RuntimeException(e.getMessage(),e);
		}
	}

	public int getEntityCount() {
		return entityIndex;
	}
	
}
