#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Thu Oct 17 09:16:37 CEST 2024
maven-metadata-osgeo-snapshot.xml.error=
maven-metadata-osgeo-snapshot.xml.lastUpdated=1729149397161
